apiVersion: v1
kind: Service
metadata:
  name: hrms-web
  namespace: hrms
  labels:
    app.kubernetes.io/name: hrms-enterprise
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    app: hrms-web
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
